import "../css/Home.css"

function Home() {
    return (
      <div>

        <h1 className="titulo">Bem-vindo ao Mundo Esportivo</h1>
        <div className="texto">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ut odio ac magna facilisis pulvinar. Nunc pretium ex hendrerit velit fermentum, quis vestibulum magna tristique. Mauris consequat efficitur nisi et tincidunt. Nunc justo arcu, consectetur et faucibus semper, consectetur vel magna. Etiam sollicitudin mi a nunc dignissim feugiat. Duis tellus ex, varius sit amet nunc finibus, blandit accumsan lectus. In semper condimentum orci at molestie. Quisque lobortis rhoncus maximus. Proin fermentum, erat non hendrerit lobortis, magna justo feugiat urna, non placerat nisl odio vitae nulla. Phasellus mollis elementum porttitor.
Fusce neque ipsum, tempus in diam id, interdum auctor est. Mauris et suscipit tellus, quis pulvinar est. Fusce ullamcorper dui mauris, nec elementum ligula mattis sed. Nam commodo tincidunt nunc eget volutpat. Cras malesuada quis ipsum ut auctor. Aenean sit amet mattis justo, quis faucibus sapien. Etiam molestie dictum molestie. Ut viverra tellus ut vehicula viverra. Duis quis efficitur sem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Ut in ornare turpis. Morbi porta pulvinar massa vitae feugiat. Proin vitae gravida neque, ac maximus dui. Integer placerat nisi diam, sit amet malesuada libero fermentum et. Suspendisse consectetur odio vitae ornare molestie. Proin lobortis purus sed lacus scelerisque venenatis. Donec pretium varius blandit. Pellentesque leo ante, rutrum quis nisl sed, lobortis porttitor quam. In ipsum erat, semper vel lobortis id, tempus ac dolor. Proin non semper diam. Suspendisse laoreet nec leo vel commodo.
Aliquam in ante et leo fermentum efficitur. Ut quis suscipit arcu. Curabitur id sagittis lectus, quis faucibus nibh. Fusce orci risus, volutpat ac aliquam eu, dictum vitae libero. Suspendisse in gravida eros, a rutrum quam. Suspendisse potenti. Phasellus ultricies ornare nunc at accumsan.
Duis varius ac quam in ullamcorper. Sed metus purus, tempor non est blandit, pharetra porttitor nisi. Mauris sed metus quis quam ornare interdum in vitae nisi. Quisque nec molestie diam. Donec aliquet, magna euismod laoreet molestie, velit metus fringilla mi, nec egestas tellus felis vel dui. Quisque sed lorem a lectus scelerisque efficitur cursus sed libero. Donec quis ligula tincidunt justo consectetur laoreet. Suspendisse potenti.
Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed gravida condimentum mi et congue. Cras pretium ullamcorper faucibus. In ipsum elit, posuere feugiat eleifend congue, accumsan at dolor. Aenean lobortis lorem nunc, id accumsan augue imperdiet in. Duis accumsan metus vitae hendrerit tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras a vestibulum lorem. Nulla sit amet ipsum lorem. Mauris quis leo ac dolor blandit dignissim id at ipsum. Ut sem justo, molestie eu felis nec, vehicula feugiat enim. Donec mattis nunc mattis turpis suscipit, et laoreet elit fermentum. Praesent quis libero tortor. Donec tincidunt ac augue vitae sagittis. Suspendisse ac diam magna.
Nam sollicitudin ut orci vitae sagittis. Nullam a interdum velit, non faucibus leo. Aenean erat lorem, scelerisque sit amet ipsum ac, porta luctus metus. Pellentesque ut est porttitor, sollicitudin diam non, blandit massa. Vivamus pharetra dui id sapien pharetra efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi dui ipsum, imperdiet non magna ac, tincidunt tempor augue. Maecenas magna dolor, pellentesque a eros pharetra, fringilla accumsan sapien. Phasellus odio mi, dictum eu purus non, viverra tristique orci. Phasellus felis diam, auctor quis justo ac, facilisis condimentum sem. Ut ac laoreet nisi. Vestibulum iaculis pulvinar nunc. Etiam tincidunt sodales erat et posuere.
Aliquam a libero eros. Morbi ac sapien tincidunt, vehicula sapien ac, tempor orci. Ut gravida est id diam maximus, id commodo orci egestas. Morbi bibendum mollis magna et convallis. Vestibulum vel mauris vel lacus maximus aliquet. Proin ultricies nec mi a euismod. Donec ac accumsan.</div>
        </div>
    );
  }
  
  export default Home;